version: '3.9'

services:
  target-old-db:
    container_name: target-old-db
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
